"use client";

import { ArrowLeft, Brain, ChevronLeft, ChevronRight, Target, Trash2, Trophy } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { Chessboard } from "react-chessboard";

type ReviewMove = { id: string; ply: number; moveNumber: number; side: string; san: string; classification: string; cpLoss: number; winDrop: number; accuracy: number; phase: string; fenBefore: string; bestMoveSan?: string; motifs: string[]; pv: string[] };
type ReviewData = { game: { id: string; white: string; black: string; result: string; opening?: string; eco?: string; userColor?: string }; review: { accuracy: number; strengths: string[]; improvements: string[]; summary: { classifications?: Record<string, number> } }; moves: ReviewMove[] };

export function GameReview({ id }: { id: string }) {
  const router = useRouter(); const [data, setData] = useState<ReviewData | null>(null); const [selected, setSelected] = useState(0);
  useEffect(() => { fetch(`/api/games/${id}`).then(async (response) => await response.json() as ReviewData).then(setData); }, [id]);
  if (!data?.review) return <main className="content-page"><div className="empty-panel"><Brain size={25} /><h2>Loading review…</h2></div></main>;
  const move = data.moves[selected]; const critical = data.moves.filter((item) => item.classification === "mistake" || item.classification === "blunder"); const classes = data.review.summary.classifications || {};
  const remove = async () => { if (!window.confirm("Delete this game and its review?")) return; await fetch(`/api/games/${id}`, { method: "DELETE" }); router.push("/analyze"); router.refresh(); };
  return <main className="content-page review-page"><div className="review-topline"><Link href="/analyze"><ArrowLeft size={16} /> All games</Link><button className="danger-link" onClick={remove}><Trash2 size={15} /> Delete game</button></div><section className="review-hero"><div><span className="eco-pill">{data.game.eco || "Review"}</span><h1>{data.game.white} <span>vs.</span> {data.game.black}</h1><p>{data.game.opening || "Opening not identified"} · {data.game.result}</p></div><div className="accuracy-ring" style={{ "--accuracy": `${data.review.accuracy * 3.6}deg` } as React.CSSProperties}><strong>{data.review.accuracy}</strong><small>accuracy</small></div></section>
    <section className="review-stat-grid"><div><small>Best</small><strong>{classes.best || 0}</strong></div><div><small>Good</small><strong>{classes.good || 0}</strong></div><div><small>Inaccuracies</small><strong>{classes.inaccuracy || 0}</strong></div><div><small>Mistakes</small><strong>{classes.mistake || 0}</strong></div><div><small>Blunders</small><strong>{classes.blunder || 0}</strong></div></section>
    <section className="review-workspace"><div className="review-board">{move && <Chessboard options={{ position: move.fenBefore, boardOrientation: data.game.userColor === "black" ? "black" : "white", lightSquareStyle: { backgroundColor: "#e7dcc4" }, darkSquareStyle: { backgroundColor: "#769656" }, boardStyle: { borderRadius: "6px", boxShadow: "0 24px 60px rgba(0,0,0,.35)" } }} />}</div><aside className="move-review-panel">{move ? <><div className="move-review-heading"><span>Move {move.moveNumber}</span><span className={`classification ${move.classification}`}>{move.classification}</span></div><h2>You played {move.san}</h2><p>Stockfish preferred <strong>{move.bestMoveSan || "another continuation"}</strong>. The move lost {move.winDrop}% winning chances and {move.cpLoss} centipawns.</p><div className="move-facts"><span>Phase <strong>{move.phase}</strong></span><span>Accuracy <strong>{move.accuracy}%</strong></span></div>{move.motifs.length > 0 && <div className="motif-list">{move.motifs.map((motif) => <span key={motif}>{motif.replaceAll("_", " ")}</span>)}</div>}<div className="engine-line"><small>Engine continuation</small><strong>{move.pv.join(" ") || "No line available"}</strong></div></> : <p>No user moves were recorded.</p>}<div className="review-controls"><button onClick={() => setSelected((value) => Math.max(0, value - 1))} disabled={selected === 0}><ChevronLeft size={17} /></button><span>{selected + 1} / {data.moves.length}</span><button onClick={() => setSelected((value) => Math.min(data.moves.length - 1, value + 1))} disabled={selected >= data.moves.length - 1}><ChevronRight size={17} /></button></div></aside></section>
    <section className="coaching-grid"><div className="coaching-card strength"><Trophy size={20} /><h2>What went well</h2>{data.review.strengths.map((item) => <p key={item}>{item}</p>)}</div><div className="coaching-card focus"><Target size={20} /><h2>Needs work</h2>{data.review.improvements.map((item) => <p key={item}>{item}</p>)}</div><div className="critical-card"><div className="section-heading"><h2>Critical moments</h2><span>{critical.length}</span></div>{critical.slice(0, 8).map((item) => <button key={item.id} onClick={() => setSelected(data.moves.indexOf(item))}><span className={`classification ${item.classification}`}>{item.classification}</span><strong>{item.moveNumber}. {item.san}</strong><small>-{item.winDrop}%</small></button>)}</div></section>
  </main>;
}
